
#' Create approximation of reward function for each scenario, used in \code{Bellman}
#'
#' @param Data_week Data frame generated in \code{Grid_Matrix} code containing
#' reward database for each scenario (we suppose there is only one week at a time)
#'
#' @return List of \code{stats::approxfun} for each scenario
#' @keywords internal
get_reward_interpolation <- function(Data_week){

  reward <- dplyr::distinct(Data_week[,c('years','reward_db')])

  f_reward_year <- sapply(reward$reward_db,FUN = function(df) stats::approxfun(df$control,df$reward))

  return(f_reward_year)
}


#' Create a data frame with all possible transition and associated next state for
#' each scenario and each state for one particular week, used in \code{Bellman}.
#' For each next state, Bellman value is calculated.
#'
#' @param Data_week Data frame generated in \code{Grid_Matrix} code containing
#' list of states and years evaluated (we suppose there is only one week at a time)
#' as weel as inflows
#' @param decision_space Simulation constraints values for the week
#'  generated by \code{get_Reward} or \code{runWaterValuesSimulation}
#' @param lvl_high Double, top rule curve for the end of the week in MWh
#' @param lvl_low Double, bottom rule curve for the end of the week in MWh
#' @param E_max Double, weekly maximum turbining power for the week
#' @param P_max Double, weekly maximum pumping power for the week
#' @param next_week_values Vector of Bellman values for the next week
#' @param niveau_max Reservoir capacity in MWh
#' @param overflow_cost Cost for overflow (equal to spillage cost of the area)
#' @param next_states possible states for next week
#'
#' @return Data frame with same format as Data week with 3 more columns :
#' next_state, control (transition to next state) and
#' next value (Bellman value of next state)
#' @keywords internal
build_all_possible_decisions <- function(Data_week,decision_space,
                                         lvl_high,lvl_low,E_max,P_max,
                                         next_week_values,niveau_max,overflow_cost,
                                         next_states){

  df_next_week <- dplyr::distinct(data.frame(
    next_state = next_states,
    next_value = next_week_values
  ))

  #Get interpolation function of next Bellman values
  f_next_value <- stats::approxfun(df_next_week$next_state, df_next_week$next_value)

  df_next_week = data.frame(next_state = c(lvl_low,lvl_high)) %>%
    dplyr::mutate(next_value=sapply(.data$next_state,f_next_value)) %>%
    rbind(df_next_week)

  future_states <- Data_week %>%
    dplyr::cross_join(df_next_week) %>%
    dplyr::mutate(control = -.data$next_state+.data$states+.data$hydroStorage)

  control_possible <- Data_week  %>%
    dplyr::right_join(decision_space,by=c("years"="mcYear"), relationship="many-to-many") %>%
    dplyr::rename("control"="u") %>%
    dplyr::mutate(next_state=dplyr::if_else(.data$states+.data$hydroStorage-.data$control>niveau_max,niveau_max,
                                            .data$states+.data$hydroStorage-.data$control)) %>%
    dplyr::mutate(overflow=dplyr::if_else(.data$states+.data$hydroStorage-.data$control>niveau_max,
                                          .data$states+.data$hydroStorage-.data$control-niveau_max,0)) %>%
    dplyr::mutate(next_value=sapply(.data$next_state,f_next_value)+
                    .data$overflow*overflow_cost) %>%
    dplyr::select(-c("overflow"))

  df_SDP <- dplyr::bind_rows(future_states, control_possible) %>%
    dplyr::filter((-P_max<=.data$control)&(.data$control<=E_max)&(.data$next_state>=0))

  return(df_SDP)
}
