#' Get the reward matrix from simulations
#'
#' @param simulation_names
#' generated by \code{runWaterValuesSimulation}
#' @param pattern A pattern to identify simulations.
#' @param district_name Name of the district used to store output.
#' @param opts
#'   List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath}
#' @param correct_monotony Binary argument (default to false). True to correct monotony of rewards.
#' @param method_old If T, linear interpolation used between simulations reward, else smarter interpolation based on marginal prices
#' @param hours If method_old=F, vector of hours used to evaluate costs/rewards of pumping/generating
#' @param possible_controls If method_old=F, vector of controls evaluated
#' @param T_max Max generating power
#' @param P_max Max pumping power
#' @param mcyears Vector of years used to evaluate rewards
#' @param area Area used to calculate watervalues
#' @param pump_eff Pumping efficiency
#' @param district_balance Name of district used to evaluate controls on the stock
#' @param ind name of simulation that corresponds to 0
#' @param simulation_values Values generated by \code{runWaterValuesSimulation}
#'
#' @return a data.table {timeid,MCyear,simulation overall cost}
#' @export
#' @import data.table
#' @importFrom assertthat assert_that
#' @importFrom antaresRead setSimulationPath readAntares getDistricts
#'



get_Reward <- function(simulation_values = NULL,simulation_names=NULL, pattern = NULL,
                       district_name = "water values district",
                       opts = antaresRead::simOptions(), correct_monotony = FALSE,
                       method_old = TRUE, hours=0:168, possible_controls = NULL,
                       T_max, P_max, mcyears = "all",area=NULL,pump_eff=NULL,
                       district_balance="water values district",ind=NaN) {
  assertthat::assert_that(class(opts) == "simOptions")
  assertthat::assert_that(district_name %in% antaresRead::getDistricts(opts=opts))
  studyPath <- opts$studyPath

  # just a test if there is a simulation done or not
  {if (is.null(simulation_names)) {
    if (is.null(pattern))
      stop("If 'simulation_names' is not provided, 'pattern' cannot be NULL.")
    simulation_names <- getSimulationNames(pattern = pattern, studyPath = studyPath)
  }}

  # this part prepare the environment of each simulation
  {
    opts_o <- lapply(
      X = simulation_names,
      FUN = function(i) {
        suppressWarnings({
          antaresRead::setSimulationPath(path = studyPath, simulation = i)
        })
      }
    )
  }

  if(method_old){

    #generate a table containing the year, the time id and OVerall cost
    {reward <- lapply(
      X = opts_o,
      FUN = function(o) {
        res <- antaresRead::readAntares(districts = district_name, mcYears = mcyears, timeStep = "weekly", opts = o)
        res <- res[timeId == 53L, timeId := 1L]
        res <- res[, lapply(.SD, sum, na.rm = TRUE), by = list(timeId, mcYear), .SDcols = "OV. COST"]
        res$simulation <- o$name
        res
      }
    )}


    reward <- rbindlist(reward)   #merge the all simulations tables together

    if (correct_monotony){
      cost <- reward
      cost$control <- cost$simulation %>%
        stringr::str_extract("\\-?\\d+$") %>% as.double()
      U <- cost %>% select("control") %>% dplyr::distinct()
      cost <- cost %>% dplyr::mutate(min_previous_reward=.data$`OV. COST`) %>%
        dplyr::arrange(.data$mcYear, .data$timeId, .data$control)
      for (u in U$control){
        cost[cost$control==u,'min_previous_reward'] <- cost %>% dplyr::filter(.data$control<=u) %>%
          dplyr::group_by(mcYear, timeId) %>%
          dplyr::mutate(min_previous_reward = min(.data$`OV. COST`)) %>%
          dplyr::ungroup %>%
          dplyr::filter(.data$control==u) %>%
          select("min_previous_reward")
      }

      cost <- cost %>% select("timeId","mcYear","simulation","min_previous_reward") %>%
        dplyr::rename(`OV. COST` = .data$min_previous_reward)

      reward <- cost[,c("timeId","mcYear","OV. COST","simulation")]
    }

    reward <- dcast(reward, timeId + mcYear ~ .data$simulation, value.var = "OV. COST")
    vars <- colnames(reward)[3:length(reward)]
    setcolorder(x = reward, neworder = c("timeId", "mcYear", vars))


    if(is.na(ind)) ind <- which(endsWith(vars,"_0"))

    reward <- reward[
      , (vars) := lapply(.SD, FUN = function(x) {
        get(vars[ind]) - x
      }),
      .SDcols = vars
    ]

    options("antares" = opts)

    output <- list()
    output$reward <- reward
    output$simulation_names <- simulation_names
    output$simulation_values <- simulation_values

  } else {
    if(is.null(pump_eff)){
      pump_eff <- getPumpEfficiency(area=area, opts = opts)
    }

    if(is.null(possible_controls)){
      nb_hours <- length(hours)
      possible_controls <- data.frame(h=1:(2*nb_hours-1)) %>%
      dplyr::mutate(i=dplyr::if_else(.data$h>nb_hours,2*nb_hours-.data$h,.data$h)) %>%
      dplyr::mutate(u=dplyr::if_else(.data$h>nb_hours,T_max*(168-hours[i]),P_max*(hours[i]-168)*pump_eff)) %>%
      dplyr::pull("u")
    }

    {reward <- mapply(
      FUN = function(o,u) {
        if (P_max>0){
          res <- get_local_reward(o,hours,possible_controls,T_max,P_max,area,mcyears,
                                  district_balance,pump_eff)
        } else {
          res <- get_local_reward_turb(o,possible_controls,T_max,area,mcyears,
                                       district_balance)
        }
        res <- reward_offset(o,res, u,mcyears,district_name)
        res
      },
      o = opts_o,
      u = simulation_values,
      SIMPLIFY = F
    )}


    reward <- rbindlist(reward)   #merge the all simulations tables together

    reward <- reward %>%
      dplyr::group_by(.data$mcYear,.data$week,.data$u) %>% dplyr::summarise(reward=min(.data$reward),.groups="drop")

    reward <- dplyr::filter(reward,.data$u==0) %>% select("mcYear","week","reward") %>%
      dplyr::right_join(reward,by=c("mcYear","week"),suffix=c("_0","")) %>%
      dplyr::mutate(reward=.data$reward-.data$reward_0) %>%
      dplyr::mutate(control=stringr::str_replace(as.character(round(.data$u/1000)),"-",".")) %>%
      dplyr::rename(timeId=.data$week) %>%
      select(-c("u","reward_0")) %>%
      pivot_wider(names_from = .data$control, values_from = .data$reward)
    reward <- as.data.table(reward)

    options("antares" = opts)

    output <- list()
    output$reward <- reward
    output$simulation_names <- colnames(reward)[3:length(reward)]
    output$simulation_values <- possible_controls
  }

  class(output) <- "Reward matrix , simulation names and values"

  return(output)

}

#' Calculate rewards for a simulation based on marginal prices
#'
#' @param opts List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath}
#' @param hours vector of hours used to evaluate costs/rewards of pumping/generating
#' @param possible_controls vector of controls evaluated
#' @param T_max Max generating power
#' @param P_max Max pumping power
#' @param area_price Area used to evaluate marginal prices
#' @param mcyears Vector of years used to evaluate rewards
#' @param district_balance Name of district used to evaluate controls on the stock
#' @param pump_eff Pumping efficiency
#'
#' @return a data.table {mcYear,week,u,reward}
#' @export
get_local_reward <- function(opts,hours,possible_controls,T_max,P_max,area_price,mcyears,
                             district_balance="water values district",pump_eff=1){
  hours <- unique(c(-hours, hours))

  price <- readAntares(areas=area_price,select=c("MRG. PRICE"),
                       opts=opts,mcYears = mcyears) %>%
    select(-c("day","month","hour","area","time")) %>%
    left_join(readAntares(districts=district_balance,select=c("BALANCE"),
                          opts=opts,mcYears = mcyears),by=c("timeId","mcYear")) %>%
    select(-c("day","month","hour","district","time")) %>%
    dplyr::mutate(week=(timeId-1)%/%168+1,hour_in_week=dplyr::if_else(timeId%%168>0,timeId%%168,168)) %>%
    dplyr::rename(price=.data$`MRG. PRICE`,balance=.data$BALANCE)


  price_turb_more <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(dplyr::desc(.data$price),.data$balance) %>%
    dplyr::mutate(reward_turb=cumsum(price*dplyr::if_else(.data$balance<0,(T_max+.data$balance),T_max)),
           vol_turb=cumsum(dplyr::if_else(.data$balance<0,(T_max+.data$balance),T_max)),
           hour_turb=.data$vol_turb/T_max) %>%
    select("mcYear","week","hour_turb","reward_turb") %>% dplyr::ungroup()
  price_turb_less <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(.data$price,dplyr::desc(.data$balance)) %>%
    dplyr::mutate(reward_turb=cumsum(price*dplyr::if_else(.data$balance<0,.data$balance,0)),
           vol_turb=cumsum(dplyr::if_else(.data$balance<0,.data$balance,0)),
           hour_turb=.data$vol_turb/T_max) %>%
    select("mcYear","week","hour_turb","reward_turb") %>% dplyr::ungroup()
  price_turb <- rbind(price_turb_less,price_turb_more) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_turb,.data$reward_turb)

  price_turb_int <- price_turb %>%
    dplyr::group_by(mcYear,week) %>%
    dplyr::arrange(.data$hour_turb) %>%
    dplyr::mutate(hour_turb_inf=round(.data$hour_turb,5),reward_turb_inf=.data$reward_turb,
           hour_turb_sup=round(dplyr::lead(.data$hour_turb),5),reward_turb_sup=dplyr::lead(.data$reward_turb)) %>%
    select(-c("hour_turb","reward_turb")) %>%
    tidyr::drop_na()

  hour_turb_0 <- price_turb %>% dplyr::group_by(mcYear,week) %>%
    dplyr::summarise(hour_turb_0=-round(min(.data$hour_turb),5),.groups="drop")

  hour_turb <- data.frame(tidyr::expand_grid(mcYear=mcyears,week=1:52,hour_turb=hours)) %>%
    rbind(select(dplyr::mutate(hour_turb_0,hour_turb=round(-.data$hour_turb_0,5)),-c("hour_turb_0"))) %>%
    rbind(select(dplyr::mutate(hour_turb_0,hour_turb=round(168-.data$hour_turb_0,5)),-c("hour_turb_0"))) %>%
    left_join(hour_turb_0,by=c("mcYear","week")) %>%
    dplyr::filter(.data$hour_turb+.data$hour_turb_0>=0,.data$hour_turb+.data$hour_turb_0<=168) %>%
    select(-c("hour_turb_0")) %>%
    left_join(price_turb_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_turb>=y$hour_turb_inf,
                                                x$hour_turb<=y$hour_turb_sup)) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_turb,.keep_all=T) %>%
    dplyr::mutate(reward_turb=dplyr::if_else(.data$hour_turb_inf!=.data$hour_turb_sup,
                               .data$reward_turb_inf+(.data$reward_turb_sup-.data$reward_turb_inf)/(.data$hour_turb_sup-.data$hour_turb_inf)*(.data$hour_turb-.data$hour_turb_inf),
                               .data$reward_turb_inf)) %>%
    select(-c("hour_turb_inf","hour_turb_sup","reward_turb_inf","reward_turb_sup"))

  price_turb_int <- hour_turb %>%
    dplyr::group_by(mcYear,week) %>%
    dplyr::arrange(.data$hour_turb) %>%
    dplyr::mutate(hour_turb_inf=round(.data$hour_turb,5),reward_turb_inf=.data$reward_turb,
           hour_turb_sup=round(dplyr::lead(.data$hour_turb),5),reward_turb_sup=dplyr::lead(.data$reward_turb)) %>%
    select(-c("hour_turb","reward_turb")) %>%
    tidyr::drop_na()

  price_pump_more <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(.data$price,dplyr::desc(.data$balance)) %>%
    dplyr::mutate(cost_pump=cumsum(price*dplyr::if_else(.data$balance>0,(P_max-.data$balance),P_max)),
           vol_pump=cumsum(dplyr::if_else(.data$balance>0,(P_max-.data$balance),P_max)),
           hour_pump=.data$vol_pump/P_max) %>%
    select("mcYear","week","hour_pump","cost_pump") %>% dplyr::ungroup()
  price_pump_less <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(dplyr::desc(.data$price),.data$balance) %>%
    dplyr::mutate(cost_pump=cumsum(price*dplyr::if_else(.data$balance>0,-.data$balance,0)),
           vol_pump=cumsum(dplyr::if_else(.data$balance>0,-.data$balance,0)),
           hour_pump=.data$vol_pump/P_max) %>%
    select("mcYear","week","hour_pump","cost_pump") %>% dplyr::ungroup()
  price_pump <- rbind(price_pump_less,price_pump_more) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_pump,.data$cost_pump)

  price_pump_int <- price_pump %>%
    dplyr::group_by(mcYear,week) %>%
    dplyr::arrange(.data$hour_pump) %>%
    dplyr::mutate(hour_pump_inf=round(.data$hour_pump,5),cost_pump_inf=.data$cost_pump,
           hour_pump_sup=round(dplyr::lead(.data$hour_pump),5),cost_pump_sup=dplyr::lead(.data$cost_pump)) %>%
    select(-c("hour_pump","cost_pump")) %>%
    tidyr::drop_na()

  hour_pump_0 <- price_pump_int %>% dplyr::group_by(mcYear,week) %>%
    dplyr::summarise(hour_pump_0=-round(min(.data$hour_pump_inf),5),.groups="drop")

  hour_pump <- data.frame(tidyr::expand_grid(mcYear=mcyears,week=1:52,hour_pump=hours)) %>%
    rbind(select(dplyr::mutate(hour_pump_0,hour_pump=round(-.data$hour_pump_0,5)),-c("hour_pump_0"))) %>%
    rbind(select(dplyr::mutate(hour_pump_0,hour_pump=round(168-.data$hour_pump_0,5)),-c("hour_pump_0"))) %>%
    left_join(hour_pump_0,by=c("mcYear","week")) %>%
    dplyr::filter(.data$hour_pump+.data$hour_pump_0>=0,.data$hour_pump+.data$hour_pump_0<=168) %>%
    select(-c("hour_pump_0")) %>%
    left_join(price_pump_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_pump>=y$hour_pump_inf,
                                                x$hour_pump<=y$hour_pump_sup)) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_pump,.keep_all=T) %>%
    dplyr::mutate(cost_pump=dplyr::if_else(.data$hour_pump_inf!=.data$hour_pump_sup,
                             .data$cost_pump_inf+(.data$cost_pump_sup-.data$cost_pump_inf)/(.data$hour_pump_sup-.data$hour_pump_inf)*(.data$hour_pump-.data$hour_pump_inf),
                             .data$cost_pump_inf)) %>%
    select(-c("hour_pump_inf","hour_pump_sup","cost_pump_inf","cost_pump_sup"))

  price_pump_int <- hour_pump %>%
    dplyr::group_by(mcYear,week) %>%
    dplyr::arrange(.data$hour_pump) %>%
    dplyr::mutate(hour_pump_inf=round(.data$hour_pump,5),cost_pump_inf=.data$cost_pump,
           hour_pump_sup=round(dplyr::lead(.data$hour_pump),5),cost_pump_sup=dplyr::lead(.data$cost_pump)) %>%
    select(-c("hour_pump","cost_pump")) %>%
    tidyr::drop_na()


  df_reward <- data.frame(tidyr::expand_grid(mcYear=mcyears,week=1:52,u=possible_controls)) %>%
    left_join(hour_turb_0,by=c("mcYear","week")) %>%
    left_join(hour_pump_0,by=c("mcYear","week"))

  df_reward_extreme <- df_reward %>%
    dplyr::mutate(hour_turb_exact=round((.data$u+168*P_max*pump_eff)/(T_max+P_max*pump_eff)-.data$hour_turb_0,5),
           hour_pump_exact=168-.data$hour_turb_exact-.data$hour_pump_0-.data$hour_turb_0) %>%
    left_join(price_turb_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_turb_exact>=y$hour_turb_inf,
                                                x$hour_turb_exact<=y$hour_turb_sup)) %>%
    dplyr::mutate(reward_turb=dplyr::if_else(.data$hour_turb_inf!=.data$hour_turb_sup,
                               .data$reward_turb_inf+(.data$reward_turb_sup-.data$reward_turb_inf)/(.data$hour_turb_sup-.data$hour_turb_inf)*(.data$hour_turb_exact-.data$hour_turb_inf),
                               .data$reward_turb_inf),
           reward_turb=round(.data$reward_turb,5)) %>%
    select(-c("hour_turb_inf","hour_turb_sup","reward_turb_inf","reward_turb_sup")) %>%
    dplyr::rename(hour_turb=.data$hour_turb_exact) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$u,.keep_all = T)

  df_reward_turb <- dplyr::full_join(hour_turb, df_reward, by=c("mcYear","week"),relationship = "many-to-many") %>%
    dplyr::mutate(hour_pump_exact=round((-.data$u+T_max*(.data$hour_turb_0+.data$hour_turb))/pump_eff/P_max-.data$hour_pump_0,5)) %>%
    dplyr::filter((.data$hour_pump_exact+.data$hour_pump_0>=0)&(.data$hour_turb+.data$hour_turb_0+.data$hour_pump_exact+.data$hour_pump_0<=168)) %>%
    rbind(df_reward_extreme) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_turb,.data$u,.keep_all = T) %>%
    left_join(price_pump_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_pump_exact>=y$hour_pump_inf,
                                                x$hour_pump_exact<=y$hour_pump_sup)) %>%
    dplyr::mutate(cost_pump=dplyr::if_else(.data$hour_pump_inf!=.data$hour_pump_sup,
                             .data$cost_pump_inf+(.data$cost_pump_sup-.data$cost_pump_inf)/(.data$hour_pump_sup-.data$hour_pump_inf)*(.data$hour_pump_exact-.data$hour_pump_inf),
                             .data$cost_pump_inf),
           reward = .data$reward_turb-.data$cost_pump) %>%
    select("mcYear","week","u","reward")

  df_reward_pump <- dplyr::full_join(hour_pump, df_reward, by=c("mcYear","week"),relationship = "many-to-many") %>%
    dplyr::mutate(hour_turb_exact=round((.data$u+P_max*pump_eff*(.data$hour_pump_0+.data$hour_pump))/T_max-.data$hour_turb_0,5)) %>%
    dplyr::filter((.data$hour_turb_exact+.data$hour_turb_0>=0)&(.data$hour_turb_exact+.data$hour_turb_0+.data$hour_pump+.data$hour_pump_0<=168)) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_pump,.data$u,.keep_all = T) %>%
    left_join(price_turb_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_turb_exact>=y$hour_turb_inf,
                                                x$hour_turb_exact<=y$hour_turb_sup)) %>%
    dplyr::mutate(reward_turb=dplyr::if_else(.data$hour_turb_inf!=.data$hour_turb_sup,
                               .data$reward_turb_inf+(.data$reward_turb_sup-.data$reward_turb_inf)/(.data$hour_turb_sup-.data$hour_turb_inf)*(.data$hour_turb_exact-.data$hour_turb_inf),
                               .data$reward_turb_inf),
           reward_turb=round(.data$reward_turb,5),
           reward = .data$reward_turb-.data$cost_pump) %>%
    select("mcYear","week","u","reward")

  df_reward <- rbind(df_reward_pump,df_reward_turb) %>%
    dplyr::group_by(.data$mcYear,.data$week,.data$u) %>%
    dplyr::slice_max(.data$reward,with_ties = F) %>% dplyr::ungroup()

  return(df_reward)

}

#' Calculate rewards for a simulation based on marginal prices for a stock with only generating power
#'
#' @param opts List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath}
#' @param possible_controls vector of controls evaluated
#' @param T_max Max generating power
#' @param area_price Area used to evaluate marginal prices
#' @param mcyears Vector of years used to evaluate rewards
#' @param district_balance Name of district used to evaluate controls on the stock
#'
#' @return a data.table {mcYear,week,u,reward}
#' @export
get_local_reward_turb <- function(opts,possible_controls,T_max,area_price,mcyears,
                                  district_balance="water values district"){
  price <- readAntares(areas=area_price,select=c("MRG. PRICE"),
                        opts=opts,mcYears = mcyears) %>%
    select(-c("day","month","hour","area","time")) %>%
    left_join(readAntares(districts=district_balance,select=c("BALANCE"),
                          opts=opts,mcYears = mcyears),by=c("timeId","mcYear")) %>%
    select(-c("day","month","hour","district","time")) %>%
    dplyr::mutate(week=(timeId-1)%/%168+1,hour_in_week=dplyr::if_else(timeId%%168>0,timeId%%168,168)) %>%
    dplyr::rename(price=.data$`MRG. PRICE`,balance=.data$BALANCE)


  price_turb_more <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(dplyr::desc(.data$price),.data$balance) %>%
    dplyr::mutate(reward_turb=cumsum(price*dplyr::if_else(.data$balance<0,(T_max+.data$balance),T_max)),
           vol_turb=cumsum(dplyr::if_else(.data$balance<0,(T_max+.data$balance),T_max)),
           hour_turb=.data$vol_turb/T_max) %>%
    select("mcYear","week","hour_turb","reward_turb") %>% dplyr::ungroup()
  price_turb_less <- price %>%
    dplyr::group_by(mcYear,week) %>% dplyr::arrange(.data$price,dplyr::desc(.data$balance)) %>%
    dplyr::mutate(reward_turb=cumsum(price*dplyr::if_else(.data$balance<0,.data$balance,0)),
           vol_turb=cumsum(dplyr::if_else(.data$balance<0,.data$balance,0)),
           hour_turb=.data$vol_turb/T_max) %>%
    select("mcYear","week","hour_turb","reward_turb") %>% dplyr::ungroup()
  price_turb <- rbind(price_turb_less,price_turb_more) %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$hour_turb,.data$reward_turb)

  hour_turb_0 <- price_turb %>% dplyr::group_by(mcYear,week) %>%
    dplyr::summarise(hour_turb_0=-min(.data$hour_turb),.groups="drop")

  price_turb_int <- price_turb %>%
    dplyr::group_by(mcYear,week) %>%
    dplyr::arrange(.data$hour_turb) %>%
    dplyr::mutate(hour_turb_inf=round(.data$hour_turb,5),reward_turb_inf=.data$reward_turb,
           hour_turb_sup=round(dplyr::lead(.data$hour_turb),5),reward_turb_sup=dplyr::lead(.data$reward_turb)) %>%
    select(-c("hour_turb","reward_turb")) %>%
    tidyr::drop_na()

  # hour_turb <- data.frame(tidyr::expand_grid(mcYear=mcyears,week=1:52,hour_turb=hours)) %>%
  #   left_join(price_turb_int, by=dplyr::join_by(mcYear,week,hour_turb>=hour_turb_inf,
  #                                        hour_turb<=hour_turb_sup)) %>%
  #   dplyr::mutate(reward_turb=dplyr::if_else(hour_turb_inf!=hour_turb_sup,
  #                         reward_turb_inf+(reward_turb_sup-reward_turb_inf)/(hour_turb_sup-hour_turb_inf)*(hour_turb-hour_turb_inf),
  #                         reward_turb_inf)) %>%
  #   select(-c(hour_turb_inf,hour_turb_sup,reward_turb_inf,reward_turb_sup))

  df_reward <- data.frame(tidyr::expand_grid(mcYear=mcyears,week=1:52,u=possible_controls)) %>%
    left_join(hour_turb_0,by=c("mcYear","week"))

  df_reward <- df_reward %>%
    dplyr::mutate(hour_turb_exact=round(.data$u/T_max-.data$hour_turb_0,5)) %>%
    left_join(price_turb_int, by=dplyr::join_by(x$mcYear==y$mcYear,
                                                x$week==y$week,
                                                x$hour_turb_exact>=y$hour_turb_inf,
                                                x$hour_turb_exact<=y$hour_turb_sup)) %>%
    dplyr::mutate(reward=dplyr::if_else(.data$hour_turb_inf!=.data$hour_turb_sup,
                          .data$reward_turb_inf+(.data$reward_turb_sup-.data$reward_turb_inf)/(.data$hour_turb_sup-.data$hour_turb_inf)*(.data$hour_turb_exact-.data$hour_turb_inf),
                          .data$reward_turb_inf),
           reward=round(.data$reward,5)) %>%
    select(-c("hour_turb_inf","hour_turb_sup","reward_turb_inf","reward_turb_sup")) %>%
    dplyr::rename(hour_turb=.data$hour_turb_exact) %>%
    select("mcYear","week","u","reward") %>%
    dplyr::distinct(.data$mcYear,.data$week,.data$u,.keep_all = T)

  return(df_reward)

}

#' Modify local reward to take into account overall cost of the simulation
#'
#' @param opts List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath}
#' @param df_reward data.table computed by the function \code{get_local_reward}
#' @param u0 Constraint value used in the simulation, NaN if none
#' @param mcyears Vector of years used to evaluate rewards
#' @param district_cost Name of district used to evaluate overall cost
#'
#' @return a data.table {mcYear,week,u,reward}
#' @export
reward_offset <- function(opts, df_reward, u0=NaN,mcyears,district_cost= "water values district"){
  cost <- antaresRead::readAntares(districts = district_cost, mcYears = mcyears,
                                   timeStep = "weekly", opts = opts, select=c("OV. COST")) %>%
    dplyr::rename(week=.data$timeId,ov_cost=.data[['OV. COST']]) %>%
    select("mcYear","week","ov_cost") %>%
    as.data.frame()
  if (!is.na(u0)){
    df_reward <- df_reward %>%
      left_join(select(dplyr::filter(df_reward,.data$u==u0),
                       "mcYear","week","reward"),
                by=c("mcYear","week"),suffix=c("","_0")) %>%
      dplyr::mutate(reward = .data$reward-.data$reward_0) %>%
      select(-c("reward_0"))
  }
  df_reward <- df_reward %>%
    left_join(cost,by=c("mcYear","week")) %>%
    dplyr::mutate(reward = .data$reward-.data$ov_cost) %>%
    select(-c("ov_cost"))
  return(df_reward)
}
