

#' Get weekly maximum hydro storage energy
#'
#' @param area An 'antares' area.
#' @param opts
#'   List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath} 
#'
#' @return Maximum energy that can be generated by hydro storage over a week.
#'
#' @examples
#' \dontrun{
#' 
#' getWeeklyMaxHydro("fr")
#' 
#' }
getWeeklyMaxHydro <- function(area, opts = antaresRead::simOptions()) {
  monthly_hydroStorage <- antaresRead::readInputTS(hydroStorageMaxPower = area, timeStep = "hourly", opts = opts)
  
  if (hasName(monthly_hydroStorage, "hstorPMaxHigh")) {
    monthly_hydroStorage[, max(hstorPMaxHigh)] * 168 / 1e6
  } else {
    monthly_hydroStorage[, max(generatingMaxPower)] * 168 / 1e6
  }
}
