
#' Calculate and plot watervalues with \code{value_node_gen}. Penalties taken into account.
#' Used in \code{Grid_Matrix}
#'
#' @param watervalues Data frame generated in \code{Grid_Matrix}
#' @param statesdt Data frame of possible states, generated in \code{Grid_Matrix}
#' @param reservoir Data frame describing rule curves, generated by \code{readReservoirLevels}
#' @param penalty_level_high Penalty for violating the bottom rule curve
#' @param penalty_level_low Penalty for violating the top rule curve
#'
#' @return Data frame with water value (vu) for each week (weeks) and each state (states).
#' vu_pen corresponds to water value without penalties
build_data_watervalues <- function(watervalues,statesdt,reservoir,
                                   penalty_level_high,penalty_level_low){
  value_nodes_dt <- value_node_gen(watervalues,statesdt,reservoir)

  value_nodes_dt <- value_nodes_dt[value_nodes_dt$weeks!=53,]

  #add penlaties
  value_nodes_dt <- value_nodes_dt %>%
    dplyr::mutate(value_nodes_dt,
           vu_pen=dplyr::case_when(states>level_high ~ vu - penalty_level_high,
                            states<level_low ~ vu + penalty_level_low,
                            TRUE ~ vu)) %>%
    dplyr::rename(vu="vu_pen",vu_pen="vu")

  print(waterValuesViz(value_nodes_dt))
  return(value_nodes_dt)

}


#' Calculate water values from Bellman values, used in \code{Grid_Matrix} and
#' \code{build_data_watervalues}
#'
#' @param watervalues an intermediate result in Grid_Matrix contains the bellman values
#' @param statesdt an intermediate result in Grid_Matrix contains the states dicretization
#' @param reservoir an intermediate result in Grid_Matrix contains the reservoir levels
value_node_gen <- function(watervalues,statesdt,reservoir){
  value_nodes_dt <- watervalues %>%
    dplyr::group_by(.data$weeks, .data$statesid) %>%
    dplyr::mutate(value_node=mean_finite(.data$value_node)) %>%
    dplyr::mutate(value_node=dplyr::if_else(!is.finite(.data$value_node),
                                            NaN,.data$value_node)) %>%
    as.data.table()

  #add reservoir
  names(reservoir)[1] <- "weeks"
  value_nodes_dt <- dplyr::mutate(value_nodes_dt, beg_week=dplyr::if_else(.data$weeks>1,.data$weeks-1,52)) %>%
    dplyr::select(-c("level_high","level_low"))
  value_nodes_dt <- dplyr::left_join(value_nodes_dt,reservoir,by=c("beg_week"="weeks")) %>%
    dplyr::select(-c("beg_week","level_avg")) %>%
    dplyr::arrange(.data$weeks, -.data$statesid) %>%
    dplyr::group_by(.data$weeks) %>%
    dplyr::mutate(value_node_dif=.data$value_node-dplyr::lag(.data$value_node),
                  states_dif=.data$states-dplyr::lag(.data$states),
                  vu=.data$value_node_dif /.data$states_dif,
                  vu=round(.data$vu,2)) %>%
    as.data.table()
  return(value_nodes_dt)
}



#' test a difference vector convergence, used in \code{Grid_Matrix}
#' @param diff_vect is a vector of water values differences
#' @param conv is the value from which the difference become converged

converged <- function(diff_vect,conv=1){
  t <- abs(diff_vect)
  t2 <- is.nan(t)
  nan_values <- length(t2[t2==T])
  numeric_values <- length(t)-nan_values

  converged_values <- length(t[t<conv]) - nan_values
  converge_percent <-  converged_values/numeric_values
  return(converge_percent)
  }

#----- Mean of finite values
#' Calculate the mean of finite values.
#' Return \code{-Inf} if all \code{-Inf}.
#' @param x numeric vector whose mean is wanted.

mean_finite <- function(x) {
  if (all(!is.finite(x))) {
    -Inf
  } else {
    mean(x[is.finite(x)])
  }
}

#------- states to percent -----
#' Convert Reservoir levels from MWh to percent of reservoir.
#' @param data  A data.table contains the statesid and states columns
#' @param states_step_ratio percent step between two successive levels.

states_to_percent <- function(data,states_step_ratio=0.01){

  # rescale levels to round percentages ranging from 0 to 100
  states_ref <- data[, .SD[1], by = c("statesid"), .SDcols = "states"]
  states_ref[, "states_percent" := 100*states_ref$states/max(states_ref$states)]

  interv <- seq(from=0,to=100,by=round(100*states_step_ratio))
  nearest_states <- states_ref$statesid[sapply(interv, function(x) which.min(abs(x - states_ref$states_percent)))]

  states_ref_0_100 <- data.table(
    states_round_percent = interv,
    statesid = nearest_states
  )

  res <- CJ(weeks = unique(data$weeks), states_round_percent = interv)

  res <- res %>%
    dplyr::left_join(dplyr::select(states_ref_0_100,
                                   c("states_round_percent",
                                     "statesid")),by=c("states_round_percent")) %>%
    dplyr::left_join(dplyr::select(data,
                                   c("weeks", "statesid",
                                     "value_node","value_node_dif","vu")),
                                   by=c("weeks", "statesid")) %>%
    as.data.table()

  return(res)
  }


#' Correct concavity of Bellman values to have nice monotony for water values,
#' used in \code{Grid_Matrix}
#'
#' @param weeks Weeks for which we want to correct concavity
#' @param df_value_node DataFrame containing bellman values
#'
#' @return vector of corrected Bellman values
correct_concavity <- function(df_value_node, weeks){

  for (s in weeks){
    df_week <- df_value_node[df_value_node$weeks==s,c("weeks","states","value_node","years")]
    df_week <- dplyr::filter(df_week,!is.na(df_week$value_node))
    df_week <- dplyr::filter(df_week,is.finite(df_week$value_node))
    df_week <- unique(df_week)
    df_week <- dplyr::arrange(df_week,.data$states,.data$years)
    n <- nrow(df_week)
    df_week$new_value <- df_week$value_node
    states <- dplyr::distinct(df_week,states) %>% dplyr::pull(states)
    for (x in states){
      df_week <- df_week %>% dplyr::filter(states==x) %>%
        dplyr::rename(value_x="new_value",states_x="states") %>%
        dplyr::select("years", "states_x", "value_x") %>%
        dplyr::right_join(df_week, by=c("years")) %>%
        dplyr::mutate(coef=(.data$new_value-.data$value_x)/(states-.data$states_x)) %>%
        dplyr::mutate(coef=dplyr::if_else(.data$coef<0,0,.data$coef))
      df_week <- df_week %>% dplyr::filter(states>x) %>% dplyr::group_by(.data$years) %>%
        dplyr::slice(which.max(.data$coef)) %>%
        dplyr::transmute(m=.data$coef,states_y=.data$states, years=.data$years) %>%
        dplyr::right_join(df_week,by="years") %>%
        dplyr::mutate(new_value=dplyr::if_else((states>.data$states_x)&(states<=.data$states_y),
                                 .data$m*(states-.data$states_x)+.data$value_x,.data$new_value)) %>%
        dplyr::select("years", "weeks", "states", "value_node", "new_value")
    }
    df_value_node[df_value_node$weeks==s,"new_value"]  <- dplyr::left_join(df_value_node[df_value_node$weeks==s,c("weeks","states","years")],
                                                                    df_week[,c("weeks","states","new_value","years")],
                                                                    by=c("weeks","states","years"))$new_value
  }
  return(df_value_node$new_value)
}
