#' Setup a simulation before running it for calculating Water Values,
#' used in \code{runWaterValuesSimulation}
#'
#' @param area The area concerned by the simulation.
#' @param fictive_area_name Name of the fictive area to create.
#' @param thermal_cluster Name of the thermal cluster to create.
#' @param overwrite If area or cluster already exists, overwrite them ?
#' @param pumping Boolean. True to take into account the pumping.
#' @param opts
#'   List of simulation parameters returned by the function
#'   \code{antaresRead::setSimulationPath}
#' @param backup List with hydro_storage, load and misc_gen backups for area
#' generated by the function \code{getBackupData}
#' @return The result of antaresRead::simOptions
#'
setupWaterValuesSimulation <- function(area,
                                       fictive_area_name = paste0("watervalue_", area),
                                       thermal_cluster = "water_value_cluster",
                                       overwrite = FALSE,
                                       opts = antaresRead::simOptions(),
                                       pumping=F,
                                       backup) {

  changeHydroManagement(opts=opts,watervalues = F, heuristic = T, area=area)

  add_fictive_fatal_prod_demand(area = area, opts = opts, load = backup$load,
                                misc_gen = backup$misc_gen)

  resetHydroStorage(area = area, opts = opts)

  # Get hydro max power
  hydro_storage_max <- get_max_hydro(area = area, opts=opts, timeStep = "hourly")

  # Prepare thermal Cluster parameters
  time_series = c(hydro_storage_max$turb, rep(0,24))
  nominalcapacity_turb <- max(hydro_storage_max$turb)
  nominalcapacity_pump <- max(hydro_storage_max$pump)

  fictive_areas <- c(paste0(fictive_area_name,"_turb"))
  if(pumping){
    fictive_areas <- c(fictive_areas,paste0(fictive_area_name,"_pump"))
  }

  for(fictive_area in fictive_areas){

    # Create fictive areas
    opts <- antaresEditObject::createArea(name = fictive_area,
                                            overwrite = overwrite,
                                            opts = opts)

    # Create thermal cluster
    if(grepl("_turb$", fictive_area)){
      opts <- antaresEditObject::createCluster(
          area = fictive_area,
          cluster_name = thermal_cluster,
          group = "other",
          unitcount = "1",
          time_series = time_series,
          nominalcapacity = nominalcapacity_turb,
          overwrite = overwrite,
          opts = opts
        )
    }

    if(grepl("_pump$", fictive_area)){
      antaresEditObject::writeInputTS(fictive_area, type = "load",
                                      data = c(hydro_storage_max$pump, rep(0,24)),
                                      opts = opts)
    }

    # Create link
    if(grepl("_turb$", fictive_area)|grepl("_pump$", fictive_area)){
     opts <- antaresEditObject::createLink(
          from = area,
          to = fictive_area,
          propertiesLink = antaresEditObject::propertiesLinkOptions(transmission_capacities = "infinite"), #
          dataLink = NULL,
          overwrite = overwrite,
          opts = opts
        )
    }

  }#end fictive areas loop

  return(opts)
}
